### PR TITLE
Fixes and new functionality in DateConverter

### PR DESCRIPTION
**Pull request by johannesvaltonen**
Fixed and refactored DateConverter to handle UTC dates by default. Added a method for converting a date to ISO string without timezone.

### CODE REVIEW

**Comment by johannesvaltonen** [comment]
"Some" changes here, what do you think @vijuhe and @wjr- ?

**Comment by vijuhe** [comment]
The input parameter type of the date conversion functions is changed from any to Date but still the functions also try to convert strings. The purpose of the original any type was to tell the user that you can try to convert anything and see from the result if it succeeded or not. Now the signature is telling that only dates are allowed as input.

**Comment by johannesvaltonen** [comment]
@vijuhe, actually, if you look a little closer, the type is changed from `any` to `Date | string`. So you can still use either type.

**Comment by vijuhe** [comment]
Oh, you can do this 😊

Good idea to make empty strings return null dates instead of empty strings.

**Comment by johannesvaltonen** [comment]
Yes. :) So everything ok with the changes in the conversion? There was actually a bug in the old implementation, that's why I added one test to the Finnish format conversion (before midnight datetime). Now all dates are handled as UTC.

**Comment by vijuhe** [comment]
Fine by me.

**Comment by wjr-** [comment]
Late to the party but looks good!

**Pull request merged**
